"""your message

Revision ID: da791c7f4b0f
Revises: 5de543398bc2
Create Date: 2025-09-13 07:55:40.537222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da791c7f4b0f'
down_revision = '5de543398bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
